### PR TITLE
Feature/graphs

### PR DESCRIPTION
**Pull request by bell0013**
Had to re:do my whole approach as I spent longer than I should have trying to layer different lines on top of themselves. 

Had to use the mutate to adjust the overall shape of the data frame in order to plot the male & female lines on the same graph. 

Need to add writing and a bit of neatening but the main content is there.

### CODE REVIEW

**Comment by lisapizzol** [comment]
Had a similar issue myself.

**Comment by lisapizzol** [comment]
Blake, 
We need two tables each. Any ideas on what the second could be in your section?
Lisa

**Comment by lisapizzol** [comment]
Could you calculate the min, Q1, median,  Q3 and max for the males per 100 female ratio and present this in a table?
I have code for this if you want me to share it and you could than just change for our data set.

**Comment by bell0013** [comment]
Yep all good I can do that! Will get to it tomorrow. Not much on at work tomorrow so I’ll be doing this during work hours

**Comment by bell0013** [comment]
Hey Lisa, 

 

I just pushed through my last changes on the main branch – accidentally – while trying to make my push work. It was literally because I had just deleted the scribble in the readme file that it wasn’t working…lol. Spent an hour trying to rebase and restore and auto merge etc… sigh. 

Anyway, I think It’s looking pretty good. I’m not sure which exactly code we should keep and which we should hide. I might leave that up to you. 

I think writing the introduction and conclusion each separately and then pushing it (without merging it) would give a good merge conflict we can use. 



Please pull the repo run the knit and have a look and tell me what you think 😊

**Comment by bell0013** [comment]
Also for future, if you right click the file up in the top right window and click ‘Diff’ it shows what I’ve been expecting to see during merge conflicts on github, but within RStudio

**Comment by lisapizzol** [comment]
Okay. So this is looking good. 
1. Are we expected to hide code, I feel that they want to see the code so lets include it all?
2. So for our introduction and conclusion do you want to create a branch each now and merge so we get conflicts? Or do we avoid them all together?
3. If you want to create the conflict then it is probably my turn to resolve it. Hence once we are ready I should pull first which you should approve and then you pull second which I will need to resolve. 
4. We also need to had the reference, which I have ready to go.
5. We also need to write an explanation in the read me file. 
Then we are done!! Yay!!!

**Comment by lisapizzol** [comment]
Also made a push to the main to fix my figure numbers since the intro and has been added it has shifted the numbers.

**Comment by bell0013** [comment]
Yeah sorry I forgot to mention that bit. It is a bit wiggly – we can adjust that at the end if needed.

 

It also doesn’t have a minimum of conflict counts so that’s nice! I must have carried that over from the previous one. 

Do you want me to work on the intro and you can write the conclusion and add your references to the end?

**Comment by bell0013** [comment]
Do we need to write in the 4 questions as well?

**Comment by lisapizzol** [comment]
We have to show evidence of both working on the intro and conlusion in some way. 
I wonder if you write the introduction first and dont include my questions and then I can add them.
I will write the conclusion first and not include your anlysis sections for you to them add them.
In terms of including the questions do you mean throughout the analysis or just in the intro and conclusion?

**Comment by bell0013** [comment]
Sounds like a plan – I’ll start writing the intro and purposely leave out the research questions but kinda leave you a spot to edit them in. And you start writing the conclusion and I’ll add some sort of spin to it after – sound good?

**Comment by bell0013** [comment]
I just opened a PR and added you as reviewer, let me know if you’re happy with this or we can adjust the approach

**Pull request merged**
