### PR TITLE
Finalise conclusion and add readme

### PR DESCRIPTION
**Pull request by bell0013**

### CODE REVIEW

**Comment by lisapizzol** [comment]
Hi Blakee,

Sorry about the tagging I was unaware you werent getting emails when a push request comes through. I get an email both times, I wonder if this is because I am the original creator of the repo. 

Anyway, it looks like we are almost done. I would like to do a final proof read tomorrow morning, if thats okay?
Then if your happy we can submit?
Lisa

**Comment by bell0013** [comment]
All good! I'm away for the night visiting family anyway but have my laptop all set up with git and R so can change anything from here.

You're getting the emails cause I'm adding you as a reviewer each time :) It's so when you're working with other people you can only notify those who are actually meant to see it and not other people who wouldn't care!

Do you happen to know if we both need to submit it or just one of us needs to submit it?

**Comment by lisapizzol** [comment]
@bell0013 
Hi Blake,

I have done my final proof read and checked we meet the criteria information outlined in the assignment. 
I know you brought this up earlier but it states that we dont have to show code in the html file unless its needed in our report. I dont think we reference the code so I have hidden all of them. Sorry for not understanding what you were talking about eariler. If you disagree with my choices here feel free to make any or all visable. 
For the refernce you have added in the marking criteria it states you need to cite it in the report text. Unless I am going crazy I dont see this, so you might need to add this.
Thanks for doing the read me file it looks great!
If your happy with what we have and once you have made any final changes you like, can you knit the html file and upload to the repo? Or let me know you are happy with what we have and I can do this if you dont want to. 
We can then submit and need to do so individually with the following included:
image

I think that means we are almost done. Yay!
Lisa

**Comment by bell0013** [comment]
Hey Lisa,

I’m attempting to do this now and having some issues with authentication from my laptop (I did my other work on desktop at home).

I’m working on it now but if you’re able to push the html document up that would be mighty helpful :/

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lisapizzol** [comment]
How annoying! All done!
I assume you are happy to submit now? Dont forget to add the pdf copy of the html file to your folder. 
Hope you are enjoying your weekend and its been a pleasure working with you. Especially since you know your way around GitHub.
Thanks heaps!
Lisa

**Comment by bell0013** [comment]
Thank you! It actually worked finally - my Mac laptop is barely ever used and a bit old so it was running a very old operating system and the way Mac deals with git wouldn’t support such an old operating system…. Thanks for patching that up!

Pleasure working with you too! Good luck in the future

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
